class ParseError(SyntaxError): ...

class MissingOpcodeError(ParseError): ...

class MissingDirectiveError(ParseError): ...

class OperandError(ParseError): ...

class InvalidLiteralError(OperandError): ...

class MissingRegisterError(OperandError): ...

class ResolverError(ValueError): ...

class CompileError(RuntimeError): ... 